set(CMAKE_SYSTEM_NAME Windows)

if(NOT DEFINED MINGW_TRIPLE OR MINGW_TRIPLE STREQUAL "")
    if(DEFINED ENV{MINGW_TRIPLE} AND NOT "$ENV{MINGW_TRIPLE}" STREQUAL "")
        set(MINGW_TRIPLE "$ENV{MINGW_TRIPLE}")
    else()
        set(MINGW_TRIPLE "x86_64-w64-mingw32")
    endif()
endif()

if(MINGW_TRIPLE MATCHES "^i[3-6]86-")
    set(CMAKE_SYSTEM_PROCESSOR x86)
else()
    set(CMAKE_SYSTEM_PROCESSOR x86_64)
endif()

if(DEFINED ENV{MINGW_BIN_DIR} AND NOT "$ENV{MINGW_BIN_DIR}" STREQUAL "")
    set(MINGW_BIN_DIR "$ENV{MINGW_BIN_DIR}")
else()
    set(MINGW_BIN_DIR "")
endif()

function(_mingw_find_tool out_var tool_name)
    if(MINGW_BIN_DIR)
        find_program(_tool_path NAMES "${MINGW_TRIPLE}-${tool_name}" PATHS "${MINGW_BIN_DIR}" NO_DEFAULT_PATH)
    endif()
    if(NOT _tool_path)
        find_program(_tool_path NAMES "${MINGW_TRIPLE}-${tool_name}")
    endif()
    if(NOT _tool_path)
        message(FATAL_ERROR "Unable to find MinGW tool: ${MINGW_TRIPLE}-${tool_name}")
    endif()
    set("${out_var}" "${_tool_path}" PARENT_SCOPE)
    unset(_tool_path CACHE)
endfunction()

function(_mingw_find_tool_any out_var)
    set(_found_tool "")
    foreach(tool_name IN LISTS ARGN)
        if(MINGW_BIN_DIR)
            find_program(_tool_path NAMES "${MINGW_TRIPLE}-${tool_name}" PATHS "${MINGW_BIN_DIR}" NO_DEFAULT_PATH)
        endif()
        if(NOT _tool_path)
            find_program(_tool_path NAMES "${MINGW_TRIPLE}-${tool_name}")
        endif()
        if(_tool_path)
            set(_found_tool "${_tool_path}")
            break()
        endif()
        unset(_tool_path CACHE)
    endforeach()
    if(NOT _found_tool)
        message(FATAL_ERROR "Unable to find MinGW tool for ${MINGW_TRIPLE}; tried: ${ARGN}")
    endif()
    set("${out_var}" "${_found_tool}" PARENT_SCOPE)
    unset(_tool_path CACHE)
endfunction()

if(DEFINED ENV{CC} AND NOT "$ENV{CC}" STREQUAL "")
    set(CMAKE_C_COMPILER "$ENV{CC}")
else()
    _mingw_find_tool_any(CMAKE_C_COMPILER gcc-posix gcc)
endif()

if(DEFINED ENV{CXX} AND NOT "$ENV{CXX}" STREQUAL "")
    set(CMAKE_CXX_COMPILER "$ENV{CXX}")
else()
    _mingw_find_tool_any(CMAKE_CXX_COMPILER g++-posix g++)
endif()

_mingw_find_tool(CMAKE_RC_COMPILER windres)
_mingw_find_tool(CMAKE_AR ar)
_mingw_find_tool(CMAKE_RANLIB ranlib)
_mingw_find_tool(CMAKE_STRIP strip)

if(DEFINED ENV{MINGW_SYSROOT} AND NOT "$ENV{MINGW_SYSROOT}" STREQUAL "")
    set(MINGW_SYSROOT "$ENV{MINGW_SYSROOT}")
endif()
if(DEFINED ENV{QT_ROOT} AND NOT "$ENV{QT_ROOT}" STREQUAL "")
    set(QT_ROOT "$ENV{QT_ROOT}")
endif()

set(CMAKE_FIND_ROOT_PATH)
if(DEFINED MINGW_SYSROOT AND NOT "${MINGW_SYSROOT}" STREQUAL "")
    list(APPEND CMAKE_FIND_ROOT_PATH "${MINGW_SYSROOT}")
endif()
if(DEFINED QT_ROOT AND NOT "${QT_ROOT}" STREQUAL "")
    list(APPEND CMAKE_FIND_ROOT_PATH "${QT_ROOT}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)

set(CMAKE_C_FLAGS_INIT "-O2")
set(CMAKE_CXX_FLAGS_INIT "-O2")
